import React from 'react';
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import PropTypes from 'prop-types';
import ChatBotProvider from '@/context/ChatBotProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ChatTT',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ChatBotProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ChatBotProvider>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};